name: photo_posting
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:

  camera: ^0.10.5+5

  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.5
  intl: ^0.18.1
  json_annotation: ^4.8.1

dev_dependencies:

  build_runner: ^2.4.6

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true
